### ISSUE TITLE
Pod crashes while running ods-ci tests for version v2.11.0

### ISSUE THREAD

**Issue by GunaKKIBM** [red-hat-data-services/ods-ci#1621]
**Description of problem:**

Pod goes to Error status while running the ods-ci tests following this Readme - [https://github.com/red-hat-data-services/ods-ci/blob/master/ods_ci/docs/ODS-CI-IMAGE-README.md#running-the-ods-ci-container-image-in-openshift ](Readme) and the following image

```
quay.io/modh/ods-ci:2.11.0
```
The issue is - the scripts and test folders are not copied in the expected path.

**Prerequisites** (if any, like setup, operators/versions):

We have all the pre requisites satisfied. as mentioned here - [https://github.com/red-hat-data-services/ods-ci/blob/master/ods_ci/docs/ODS-CI-IMAGE-README.md#running-the-ods-ci-container-image-in-openshift]

**Steps to Reproduce**

For both pre requisites and steps to deploy - this doc was being followed, rather than building a custom image - I used quay.io/modh/ods-ci:v2.11.0

**Actual results:**
```
RUN SCRIPT ARGS: --test-variables-file /tmp/ods-ci-test-variables/test-variables.yml --skip-oclogin true --set-urls-variables true --include Smoke
ROBOT EXTRA ARGS: -L DEBUG --dryrun
SET TEST ENVIRONMENT: 0
-- USE OCM to install IDPs: 1
-----| ODS-CI is starting the tests run...|-----
./ods_ci/build/run.sh: line 28: ./run_robot_test.sh: No such file or directory
```

Also. looks like the tests folder isn't copied properly either

```
skipping OC login as per parameter --skip-oclogin
[ ERROR ] Parsing '/tmp/ods-ci/tests/Tests' failed: File or directory to execute does not exist.
```

**Expected results:**
The tests should run and show some results, this is a part of the output is from pod logs from the image that was custom built
```
Tests.Model Serving.Model Serving Modelmesh
==============================================================================
Verify Model Serving Installation :: Verifies that the core compon... | PASS |
------------------------------------------------------------------------------
Verify Openvino_IR Model Via UI :: Test the deployment of an openv... | PASS |
------------------------------------------------------------------------------
Test Inference Without Token Authentication :: Test the inference ... | PASS |
------------------------------------------------------------------------------
Tests.Model Serving.Model Serving Modelmesh                           | PASS |
3 tests, 3 passed, 0 failed
```

**Reproducibility** (Always/Intermittent/Only Once):
Always

Workaround:
Building a custom image with appropriate changes in Dockerfile.

**Comment by GunaKKIBM** [comment]
Adding to this, the readme doesn't explain about the variables expected - [https://github.com/red-hat-data-services/ods-ci/tree/master?tab=readme-ov-file](Readme)
A small note about, why these test users and AWS credentials are necessary - what it is referring to, any hyperlink, which suggests what tests are run using these would be helpful - [https://github.com/red-hat-data-services/ods-ci/blob/master/ods_ci/test-variables.yml.example](Readme)

**Comment by CFSNM** [comment]
@GunaKKIBM Hi, I raised https://github.com/red-hat-data-services/ods-ci/pull/1622 to fix this issue

**Comment by CFSNM** [comment]
@GunaKKIBM related to your questions:

1) You are right, the README does not mention anything about the variables expected. We will add information about them, but the expected variables follow the structure of [https://github.com/red-hat-data-services/ods-ci/blob/master/ods_ci/test-variables.yml.example](https://github.com/red-hat-data-services/ods-ci/issues/Readme)

2) The users are necessary for some of the workbench tests. There are some robot keywords that accept different users to test the operation from the user perspective. E.g.: https://github.com/red-hat-data-services/ods-ci/blob/e0ca2933e91c781fceb935560a03cecddb8beaba/ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/Projects.resource#L278

About the AWS credentials, they are used to create data connections for our tests. E.g.: https://github.com/red-hat-data-services/ods-ci/blob/e0ca2933e91c781fceb935560a03cecddb8beaba/ods_ci/tests/Resources/Page/ODH/ODHDashboard/ODHDataScienceProject/DataConnections.resource#L26

**Comment by CFSNM** [comment]
@GunaKKIBM hey, the images have been rebuild to pickup the fix. Please, let us know if you are still facing some issues

**Comment by GunaKKIBM** [comment]
@CFSNM , thanks, the issue is fixed in the latest image. I am currently working using the test variables, if I see any concern there, I will update.

**Comment by GunaKKIBM** [comment]
@CFSNM , I would want to understand more on what the users here, is this users of type user.openshift.io/v1 resource in openshift? I understand these values are used for testing, but I am unclear about where these values should be extracted from.

**Comment by GunaKKIBM** [comment]
Hi @CFSNM . Yes.
